Módulo Central/django-aula-master/aula/aula/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^home/', include('home.urls', namespace='home', app_name='home')),
    url(r'^usuarios/', include('usuarios.urls', namespace='usuarios', app_name='usuarios')),
    url(r'^identificacion/', include('identificacion.urls', namespace='identificacion', app_name='identificacion')),
    url(r'^musica/', include('musica.urls', namespace='musica', app_name='musica')),
    url(r'^imagenes/', include('imagenes.urls', namespace='imagenes', app_name='imagenes')),
    url(r'^multimedia/', include('multimedia.urls', namespace='multimedia', app_name='multimedia')),
    url(r'^admin/', admin.site.urls),
]

Módulo Central/django-aula-master/aula/identificacion/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url('^nuevo/$', views.nuevo, name='nuevo'),
    url('^editar/$', views.editar, name='editar'),
    url('^identificar/$', views.identificar, name='identificar'),
    url('^borrar/$', views.borrar, name='borrar'),
]

Módulo Central/django-aula-master/aula/identificacion/models.py
from __future__ import unicode_literals

import sys    # sys.setdefaultencoding is cancelled by site.py
reload(sys)    # to re-enable sys.setdefaultencoding()
sys.setdefaultencoding('utf-8')

from django.db import models
from usuarios.models import Usersys


# Create your models here.
class Type(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Identify(models.Model):
    string = models.CharField(max_length=255)
    usersys = models.ForeignKey(Usersys, on_delete=models.CASCADE, default=None, null=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.string

Módulo Central/django-aula-master/aula/identificacion/forms.py
# -*- coding: utf-8 -*-
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
from crispy_forms.bootstrap import (
    PrependedText, PrependedAppendedText, FormActions)
from usuarios.models import Usersys


class AddId(forms.Form):
    my_default_errors = {
        'required': 'Campo requerido',
        'invalid': 'Valores inválidos'
    }

    Usuario = forms.ModelChoiceField(required=True, queryset=Usersys.objects.all())
    # Tipo = forms.ModelChoiceField(required=True, queryset=Type.objects.all())
    String = forms.CharField(required=True, label='Cadena de identificacion')

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_action = '/identificacion/nuevo/'
    helper.add_input(Submit('Agregar', 'Agregar', css_class='btn-primary'))

Módulo Central/django-aula-master/aula/identificacion/views.py
from django.core import serializers
import json
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from usuarios.models import Usersys

from .models import Type, Identify
from .forms import AddId


# Create your views here.
def index(request):
    users = Usersys.objects.all()

    form = AddId()

    context = {'users': users, 'form': form}
    return render(request, 'identificacion/index.html', context)


def nuevo(request):
    users = Usersys.objects.all()

    # print request
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = AddId(request.POST)

        # check whether it's valid:
        if form.is_valid():
            rfid = Type.objects.get(name='rfid')
            user = Usersys.objects.get(pk=request.POST['Usuario'])
            new = Identify(string=request.POST['String'], usersys=user, type=rfid)
            new.save()

            print rfid
            print user


            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/identificacion/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = AddId()

    context = {'users': users, 'form': form}
    return render(request, 'identificacion/index.html', context)


def editar(request):
    print "En editar"

    cards = json.loads(request.POST.get('cards'))

    for card in cards:
        id = card['id']
        string = card['string']
        idcard = Identify.objects.get(pk=id)
        idcard.string = string
        idcard.save()

    data = 'success'
    return HttpResponse(data)


def identificar(request):
    print "En identify"
    list = []
    userId = request.GET['userId']
    idSet = Identify.objects.all()
    idSet = idSet.filter(usersys=userId)

    for row in idSet:
        list.append ({'user': row.usersys.name, 'string': row.string, 'id': row.pk})

    # data = serializers.serialize("json", list)
    data = json.dumps(list)

    # data['user'] = Usersys.objects.get(pk=userId)
    return HttpResponse(data, content_type='application/json')


def borrar(request):
    id = request.POST['id']
    card = Identify.objects.get(pk=id)

    card.delete()

    data = 'success'
    return HttpResponse(data)

Módulo Central/django-aula-master/aula/identificacion/templates/identificacion/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
  <h1 class="title">Identificación</h1>
  <div class="row">
    <div class="col-md-5 left">
      <div class="row"><h2>Lista de usuarios</h2></div>
      <div class="row">
        <table>
          <tbody>
          <tr>
            <th>Usuario</th>
            <th>Llaves</th>
            <th>Editar</th>
          </tr>
          {% for user in users %}
            <tr>
              <td>{{ user.name }} {{ user.last_names }}</td>
              <td>
                {% if user.identify_set.all %}
                  <ul>
                    {% for id in user.identify_set.all %}
                      <li>{{ id.type }}: {{ id.string }}</li>
                    {% endfor %}
                  </ul>
                {% else %}
                  No hay llaves asignadas
                {% endif %}
              </td>
              <td><img id="{{ user.id }}" class="edit-id" src="{% static 'img/edit.png' %}"></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-offset-1 col-md-6 right">
      <div class="row"><h2>Modificaciones</h2></div>
      <div class="row">
        <div class="col-md-8">
          {% crispy form %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block modal_body %}
  <div id="edit-id-content"></div>
{% endblock %}

{% block scripts %}
  <script src="{% static 'js/identificacion.js' %}"></script>
{% endblock %}